# Generated by Django 3.2.8 on 2021-10-09 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='sale_data',
            new_name='sale_date',
        ),
    ]
