# Generated by Django 3.2.8 on 2021-10-09 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_id_product_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_value',
            new_name='supplier_value',
        ),
    ]
